/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef RFS_H_RFS_YANG_KUNLUN
#define RFS_H_RFS_YANG_KUNLUN

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdlib.h>
typedef int64_t RFILE;

void rfs_init_rfs(const char *server);
void rfs_close_rfs();

RFILE rfs_fopen(const char *path, const char *mode);
size_t rfs_fread(void *ptr, size_t size, size_t nmemb, RFILE stream);
size_t rfs_fwrite(const void *ptr, size_t size, size_t nmemb, RFILE stream);
int rfs_fclose(RFILE stream);

#ifdef __cplusplus
}
#endif

#endif /* !RFS_H_RFS_YANG_KUNLUN */
